
class SVG:
    @property
    def width(self) -> float: ...

    @property
    def height(self) -> float: ...

class Parser:
    @staticmethod
    def parse(svg: str, dpi: str = ...) -> SVG: ...

    @staticmethod
    def parse_file(filename: str, dpi: str = ...) -> SVG: ...

class Rasterizer:
    def rasterize(self, svg: SVG, width: int, height: int, scale: float = ..., tx: int = ..., ty: int = ...) -> bytes: ...
    def rasterize_to_buffer(self, svg: SVG, width: int, height: int, stride: int, buffer: bytes, scale: float = ..., tx: int = ..., ty: int = ...) -> bytes: ...